name: "Wasp Deploy"
description: "Deploy with Wasp to Fly.io"
inputs:
  fly-token:
    description: "Fly.io API token"
    required: true
  server-url:
    description: "Server URL for the React app"
    required: false
  wasp-version:
    description: "Version of Wasp to use for deployment"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Install Wasp
      shell: bash
      run: |
        VERSION_PARAM=""
        if [ -n "${{ inputs.wasp-version }}" ]; then
          VERSION_PARAM="-v ${{ inputs.wasp-version }}"
        fi
        curl -sSL https://get.wasp.sh/installer.sh | sh -s -- $VERSION_PARAM

    - name: Install Flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy
      run: |
        if [ -n "${{ inputs.server-url }}" ]; then
          REACT_APP_API_URL=${{ inputs.server-url }} wasp deploy fly deploy
        else
          wasp deploy fly deploy
        fi
      shell: bash
      env:
        FLY_API_TOKEN: ${{ inputs.fly-token }}
