name: "Wasp Deploy"
description: "Deploy with Wasp to Fly.io or Railway"
inputs:
  platform:
    description: "Deployment platform: 'fly' or 'railway'"
    required: true
  fly-token:
    description: "Fly.io API token (required when platform is 'fly')"
    required: false
  railway-token:
    description: "Railway API token (required when platform is 'railway')"
    required: false
  project-name:
    description: "Project/app name (required for Railway, max 25 characters)"
    required: false
  server-url:
    description: "Server URL used by the React app"
    required: false
  wasp-version:
    description: "Version of Wasp to use for deployment"
    required: false
  node-version:
    description: "Node.js version to use"
    required: false
    default: "22"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install Wasp
      shell: bash
      run: |
        VERSION_PARAM=""
        if [ -n "${{ inputs.wasp-version }}" ]; then
          VERSION_PARAM="-v ${{ inputs.wasp-version }}"
        fi
        curl -sSL https://get.wasp.sh/installer.sh | sh -s -- $VERSION_PARAM

    - name: Install Flyctl
      if: ${{ inputs.platform == 'fly' }}
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Install Railway CLI
      if: ${{ inputs.platform == 'railway' }}
      shell: bash
      run: |
        npm install -g @railway/cli
        railway --version

    - name: Set custom server URL if provided
      shell: bash
      run: |
        if [ -n "${{ inputs.server-url }}" ]; then
          echo "REACT_APP_API_URL=${{ inputs.server-url }}" >> $GITHUB_ENV
        fi

    - name: Deploy to Fly.io
      if: ${{ inputs.platform == 'fly' }}
      shell: bash
      run: wasp deploy fly deploy
      env:
        FLY_API_TOKEN: ${{ inputs.fly-token }}

    - name: Deploy to Railway
      if: ${{ inputs.platform == 'railway' }}
      shell: bash
      run: wasp deploy railway deploy "${{ inputs.project-name }}"
      env:
        RAILWAY_API_TOKEN: ${{ inputs.railway-token }}
